"""Create hierarchical story schema

Revision ID: 686d51beb1b0
Revises: 
Create Date: 2025-06-17 20:17:24.272545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686d51beb1b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('github_repository', sa.String(length=255), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epics_id'), 'epics', ['id'], unique=False)
    op.create_index(op.f('ix_epics_status'), 'epics', ['status'], unique=False)
    op.create_index(op.f('ix_epics_story_id'), 'epics', ['story_id'], unique=True)
    op.create_index(op.f('ix_epics_title'), 'epics', ['title'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story_id', sa.String(length=50), nullable=False),
    sa.Column('epic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('synthesized_analysis', sa.Text(), nullable=True),
    sa.Column('expert_analyses_count', sa.Integer(), nullable=True),
    sa.Column('target_repositories', sa.JSON(), nullable=True),
    sa.Column('github_repository', sa.String(length=255), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_epic_id'), 'stories', ['epic_id'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_index(op.f('ix_stories_status'), 'stories', ['status'], unique=False)
    op.create_index(op.f('ix_stories_story_id'), 'stories', ['story_id'], unique=True)
    op.create_index(op.f('ix_stories_title'), 'stories', ['title'], unique=False)
    op.create_table('sub_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story_id', sa.String(length=50), nullable=False),
    sa.Column('story_id_fk', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('technical_requirements', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('github_repository', sa.String(length=255), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('assigned_role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id_fk'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_stories_id'), 'sub_stories', ['id'], unique=False)
    op.create_index(op.f('ix_sub_stories_status'), 'sub_stories', ['status'], unique=False)
    op.create_index(op.f('ix_sub_stories_story_id'), 'sub_stories', ['story_id'], unique=True)
    op.create_index(op.f('ix_sub_stories_story_id_fk'), 'sub_stories', ['story_id_fk'], unique=False)
    op.create_index(op.f('ix_sub_stories_title'), 'sub_stories', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_stories_title'), table_name='sub_stories')
    op.drop_index(op.f('ix_sub_stories_story_id_fk'), table_name='sub_stories')
    op.drop_index(op.f('ix_sub_stories_story_id'), table_name='sub_stories')
    op.drop_index(op.f('ix_sub_stories_status'), table_name='sub_stories')
    op.drop_index(op.f('ix_sub_stories_id'), table_name='sub_stories')
    op.drop_table('sub_stories')
    op.drop_index(op.f('ix_stories_title'), table_name='stories')
    op.drop_index(op.f('ix_stories_story_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_status'), table_name='stories')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_epic_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_epics_title'), table_name='epics')
    op.drop_index(op.f('ix_epics_story_id'), table_name='epics')
    op.drop_index(op.f('ix_epics_status'), table_name='epics')
    op.drop_index(op.f('ix_epics_id'), table_name='epics')
    op.drop_table('epics')
    # ### end Alembic commands ###
